name: Unit and functional tests

on:
  push:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install ".[test]"
      - run: pytest -v tests/unit-tests

  functional-test-qdrant:
    runs-on: ubuntu-latest
    services:
      qdrant:
        image: qdrant/qdrant
        ports:
          - 6333:6333
          - 6334:6334
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install ".[test, qdrant]"
      - run: pytest -v tests/functional-tests/test_qdrant.py

  functional-test-weaviate:
    runs-on: ubuntu-latest
    services:
      qdrant:
        image: cr.weaviate.io/semitechnologies/weaviate
        ports:
          - 8080:8080
          - 50051:50051
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install ".[test, weaviate]"
      - run: pytest -v tests/functional-tests/test_weaviate.py
